# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alberto Garcia-Garcia
description: > # this means to ignore newlines until "baseurl:"
  PhD Student
repository: https://github.com/Blitzman/web-revamp
baseurl: /~agarcia  # the subpath of your site, e.g. /blog
url: http://www.dtic.ua.es  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Alberto Garcia-Garcia
email: agarcia@dtic.ua.es

navigation:
  - text: Home
    url: /
  - text: Education
    url: /education
  - text: Experience
    url: /experience
  - text: Research
    url: /research
  - text: Publications
    url: /publications
  - text: CV/Resume
    url: /cv
  - text: Personal Blog
    url: /blog

projects:
  - name: git-secret
    description: A bash-tool to store your private data inside a git repository.
    link: https://sobolevn.github.io/git-secret
    image: https://github.com/sobolevn/git-secret/blob/7c9ae0b1853d4c15549027524121b9e40219fe47/images/git-secret-sm.png?raw=true
  - name: awesome-cryptography
    description: A curated list of cryptography resources and links.
    link: https://github.com/sobolevn/awesome-cryptography
    image: https://pbs.twimg.com/profile_images/751426570607271937/vGxpniun_400x400.jpg
  - name: ecto_autoslug_field
    description: Automatically creates slugs for your Ecto models.
    link: https://github.com/sobolevn/ecto_autoslug_field
  - name: django-split-settings
    description: Organize Django settings into multiple files and directories. Easily override and modify settings. Use wildcards and optional settings files.
    link: https://github.com/sobolevn/django-split-settings

social:
  - service: mail
    username: agarcia@dtic.ua.es
    link: mailto:agarcia@dtic.ua.es
  - service: scholar
    username: Scholar
    link: https://scholar.google.com/citations?user=SQ2viFYAAAAJ
  - service: researchgate
    username: ResearchGate
    link: https://www.researchgate.net/profile/Alberto_Garcia-Garcia
  - service: github
    username: GitHub
    link: https://github.com/blitzman
  - service: linkedin
    username: LinkedIn
    link: https://www.linkedin.com/in/agarciag
  - service: twitter
    username: Twitter
    link: https://twitter.com/albertgarcia93
  - service: instagram
    username: Instagram
    link: https://www.instagram.com/albert.garcia.garcia

# Plugins
gems:
  - jekyll-seo-tag
