# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alberto Garcia-Garcia
description: > # this means to ignore newlines until "baseurl:"
  PhD Student
repository: https://github.com/Blitzman/web-revamp
baseurl: /~agarcia/ # the subpath of your site, e.g. /blog
url: http://www.dtic.ua.es  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Alberto Garcia-Garcia
email: agarcia@dtic.ua.es

navigation:
  - text: Home
    url: /
  - text: Education
    url: /education
  - text: Experience
    url: /experience
  - text: Research
    url: /research
  - text: Projects
    url: /projects
  - text: Publications
    url: /publications
  - text: CV/Resume
    url: /files/cv.pdf
  - text: Personal Blog
    url: /blog
  - text: Photos
    url: /photos

research:
  - name: Interactive 3D Object Recognition Pipeline on Mobile GPGPU Computing Platforms using Low-cost RGB-D Sensors
    description: In this work, we propose the implementation of a 3D object recognition system which will be optimized to operate under demanding time constraints. The system must be robust so that objects can be recognized properly in poor light conditions and cluttered scenes with significant levels of occlusion.
    link: /research/3d_object_recognition_jetson_tk1
    image: /images/research/3d_object_recognition_jetson_tk1/grouping.png

projects:
  - name: Self-Driving Car Nanodegree | Project 2 - Traffic Sign Classifier
    description: In this project, we used deep neural networks (convolutional neural networks) to classify traffic signs. Specifically, we trained a model to classify traffic signs from the German Traffic Sign Dataset. 
    link: /projects/carnd-term1-p2-trafficsignclassifier/carnd-term1-p2-trafficsignclassifier
    image: /images/projects/carnd-term1-p2-trafficsignclassifier.png
  - name: Self-Driving Car Nanodegree | Project 1 - Finding Lane Lines
    description: In this project, we intended to identify lane lines on the road, first in an image, and later in a video stream. Our first goal was to write code including a series of steps (pipeline) that identify and draw the lane lines on a few test images. Once we could successfully identify the lines in an image, we ran the code on a video stream. The next goal was to then refine our pipeline with parameter tuning and by averaging and extrapolating the lines. At last, we tackled a challenge video.
    link: /projects/carnd-term1-p1-lanelines/carnd-term1-p1-lanelines
    image: /images/projects/carnd-p1-lanelines.png

albums:
  - name: She
    description: Friend make sense of me, friend make sense of me...
    image: /images/albums/she.jpg
  - name: Seattle
    description: To some extent, Seattle remains a frontier metropolis, a place where people can experiment with their lives, change, grow, and make things happen...
    image: /images/albums/seattle.jpg
  - name: Ludovico
    description: Taken right before Ludovico Einaudi's concert at the Moore Theatre in downtown Seattle.
    image: /images/albums/ludovico.jpg
  - name: Firefighters
    description: Thanks for giving the sun back...
    image: /images/albums/firefighters.jpg

social:
  - service: mail
    username: agarcia@dtic.ua.es
    link: mailto:agarcia@dtic.ua.es
  - service: scholar
    username: Scholar
    link: https://scholar.google.com/citations?user=SQ2viFYAAAAJ
  - service: researchgate
    username: ResearchGate
    link: https://www.researchgate.net/profile/Alberto_Garcia-Garcia
  - service: github
    username: GitHub
    link: https://github.com/blitzman
  - service: linkedin
    username: LinkedIn
    link: https://www.linkedin.com/in/agarciag
  - service: twitter
    username: Twitter
    link: https://twitter.com/albertgarcia93
  - service: instagram
    username: Instagram
    link: https://www.instagram.com/albert.garcia.garcia

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
